apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apimicroservice
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  syncPolicy:
    automated: {}
  destination:
    namespace: dev
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: apimicroservice
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    helm:
      valueFiles:
        #- secrets+gpg-import:///helm-secrets-private-keys/key.asc?values-sec.yaml
      - values.yaml
      - values-tag.yaml
